### ISSUE TITLE
crash: list index out of range

### ISSUE THREAD

**Issue by Artoria2e5** [huntzhan/zhlint#7]
Python 2.7.10 (cygwin), zhlint 0.3.2 (pip), input file https://github.com/noffle/art-of-readme/blob/2d444ca/README-zh.md:

```
$ zhlint fix README-zh.md
Traceback (most recent call last):
  File "/usr/bin/zhlint", line 11, in <module>
    sys.exit(entry_point())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zhlint/main.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zhlint/main.py", line 67, in fix
    correction_handler = ErrorCorrectionHandler(file_content, text_elements)
  File "/usr/lib/python2.7/site-packages/zhlint/error_correction.py", line 516, in __init__
    self.generate_index_matrix()
  File "/usr/lib/python2.7/site-packages/zhlint/error_correction.py", line 582, in generate_index_matrix
    while not self.lcs_matrix[row][rawcol]:
IndexError: list index out of range
```

**Comment by Artoria2e5** [comment]
话说这个 `--debug` 明明是 profile 嘛……

**Comment by huntzhan** [comment]
Working on it. The code base is a disaster. I'm thinking about refactoring it.
